name: stagexl_particle
version: 1.0.0
author: Bernhard Pichler <support@stagexl.org>
description: The particle emitter runtime for the StageXL library.
homepage: http://www.stagexl.org

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  stagexl: ^2.0.0

dev_dependencies:
  pedantic: any
  build_runner: ^2.0.4
  build_test: ^2.1.0
  build_web_compilers: ^3.0.0
