name: stagexl_particle
version: 0.3.7
author: Bernhard Pichler <support@stagexl.org>
description: The particle emitter runtime for the StageXL library.
homepage: http://www.stagexl.org
environment:
  sdk: '>=1.13.0 <2.0.0'
dependencies:
  browser: any
  stagexl: '>=0.13.0 <0.14.0'

transformers:
- $dart2js:
    commandLineOptions: ["--trust-type-annotations", "--trust-primitives", "--dump-info"]
    minify: true

